version: 0.0
os: linux
files:
  - source: /
    # destination: /var/www/myapp
    destination: /home/ec2-user/wpp-server
permissions:
  # - object: /var/www/myapp
  - object: /home/ec2-user/wpp-server
    pattern: '**'
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 900
      runas: root
